cleanup

diff --git a/.local/bin/cov2pape b/.local/bin/cov2pape
--- a/.local/bin/cov2pape
+++ b/.local/bin/cov2pape
@@ -5,12 +5,17 @@ finish () {
 }
 trap finish EXIT
 
+die () {
+    >&2 echo "$@"
+    exit 1
+}
+
 BGFILE=$(mktemp -t cov2papebg.XXXXXXXX)
 FGFILE=$(mktemp -t cov2papefg.XXXXXXXX)
 
 cover=$1
 
-[ -f "$cover" ] || exit 1
+[ -f "$cover" ] || die "${cover}: no such file"
 
 initheight=$(identify -format "%h\n" "$cover")
 
@@ -27,18 +32,17 @@ elif [ "$initheight" -ge 720  ]; then
     height=720
     width=1280
 else
-    >&2 echo "Img 2 smoll!"
-    exit 1
+    die "Img 2 smoll!"
 fi
 
 convert "$cover" -resize "$width" -gravity center \
         -extent "$width"x"$height" -blur 60x20 "$BGFILE" \
-    || exit 2
+    || die "BG resize failed"
 
 convert "$cover" -resize x"$height" "$FGFILE" \
-    || exit 2
+    || die "FG resize failed"
 
 composite -gravity center "$FGFILE" "$BGFILE" cov2pape_wallpaper.png \
-    || exit 2
+    || die "composite failed"
 
 exit 0
diff --git a/.local/bin/ytsb b/.local/bin/ytsb
--- a/.local/bin/ytsb
+++ b/.local/bin/ytsb
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+die () {
+    notify-send -- "$2" "$3"
+    exit "$1"
+}
+
 urlsfile="${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls"
 
 url="$(xclip -o -selection primary)"
@@ -10,8 +15,8 @@ case "$url" in
          grep -o 'channel-external-id="[A-Za-z0-9_-]*"' |
          sort -u |
          cut -d '"' -f 2)
-  [ -z "$id" ] && notify-send "Invalid channel-external-id" && exit 1
-  grep -q "$id" "$urlsfile" && notify-send "Already added." && exit 0
+  [ -n "$id" ] || die 1 "Invalid channel-external-id"
+  grep -q "$id" "$urlsfile" && die 0 "Already added."
   rss="https://www.youtube.com/feeds/videos.xml?channel_id=${id} yt"
   ;;
 *bitchute.com*)
@@ -19,13 +24,12 @@ case "$url" in
          grep -oi "/channel/[^/]*" |
          head -1 |
          sed "s/\ /%20/g")
-  [ -z "$id" ] && notify-send "Invalid channel-id" && exit 1
-  grep -q  "$id" "$urlsfile" && notify-send "Already added." && exit 0
+  [ -n "$id" ] || die 1 "Invalid channel-id"
+  grep -q  "$id" "$urlsfile" && die 0 "Already added."
   rss="https://www.bitchute.com/feeds/rss${id} bitchute"
   ;;
 *)
-  notify-send "Invalid URL" "$url"
-  exit 1
+  die 2 "Invalid URL" "$url"
   ;;
 esac
 
